branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts:
          - 'Lint / eslint'
          - 'CI / tests'
          - 'CI (Playwright Container) / tests'
          - 'UAT / uat'
      allow_force_pushes: false
      restrictions:
        users: []
        teams: []
        apps: []
