const SESSION_MAX_AGE_DAYS = 30;
const SESSION_MAX_AGE_SECONDS = SESSION_MAX_AGE_DAYS * 24 * 60 * 60;
const SESSION_MAX_AGE_MS = SESSION_MAX_AGE_SECONDS * 1000;

module.exports = {
  SESSION_MAX_AGE_DAYS,
  SESSION_MAX_AGE_SECONDS,
  SESSION_MAX_AGE_MS
};
