const {
  TurnPhase,
  createContinent,
  createGameState,
  createPlayer,
  createTerritory
} = require("./core-domain.cjs");
const {
  STANDARD_DICE_RULE_SET_ID,
  THREE_DEFENSE_DICE_RULE_SET_ID,
  findDiceRuleSet,
  getDiceRuleSet,
  listDiceRuleSets,
  standardDiceRuleSet
} = require("./dice.cjs");
const {
  DEFAULT_GAME_RULESET_ID,
  DEFAULT_PIECE_THEME_ID,
  DEFAULT_RULE_MODIFIER_ID,
  DEFAULT_VICTORY_RULE_ID,
  createGameRulesetDefinition,
  createPieceThemeDefinition,
  createResolvedGameConfig,
  createVictoryRuleDefinition,
  getCombatRuleDefinition,
  getGameRulesetDefinition,
  getMapDefinition,
  getPieceThemeDefinition,
  getVictoryRuleDefinition,
  listCombatRuleDefinitions,
  listGameRulesetDefinitions,
  listMapDefinitions,
  listPieceThemeDefinitions,
  listRuleModifierManifests,
  listVictoryModuleManifests,
  listVictoryRuleDefinitions,
  normalizeMapDefinition,
  summarizeMapDefinition
} = require("./engine-definitions.cjs");
const {
  CardType,
  STANDARD_CARD_RULE_SET_ID,
  STANDARD_MAX_HAND_BEFORE_FORCED_TRADE,
  createCard,
  createStandardDeck,
  getCardRuleSet,
  standardCardRuleSet,
  standardTradeBonusForIndex,
  validateStandardCardSet
} = require("./cards.cjs");
const { GameAction } = require("./game-actions.cjs");
const {
  createActionFailure,
  createDomainFailure,
  createLogEntry,
  createLocalizedError,
  createValidationFailure
} = require("./messages.cjs");

module.exports = {
  CardType,
  GameAction,
  DEFAULT_GAME_RULESET_ID,
  DEFAULT_PIECE_THEME_ID,
  DEFAULT_RULE_MODIFIER_ID,
  DEFAULT_VICTORY_RULE_ID,
  STANDARD_DICE_RULE_SET_ID,
  THREE_DEFENSE_DICE_RULE_SET_ID,
  findDiceRuleSet,
  getDiceRuleSet,
  getCombatRuleDefinition,
  getGameRulesetDefinition,
  getMapDefinition,
  getPieceThemeDefinition,
  getVictoryRuleDefinition,
  listDiceRuleSets,
  listCombatRuleDefinitions,
  listGameRulesetDefinitions,
  listMapDefinitions,
  listPieceThemeDefinitions,
  listRuleModifierManifests,
  listVictoryModuleManifests,
  listVictoryRuleDefinitions,
  normalizeMapDefinition,
  summarizeMapDefinition,
  standardDiceRuleSet,
  STANDARD_CARD_RULE_SET_ID,
  STANDARD_MAX_HAND_BEFORE_FORCED_TRADE,
  TurnPhase,
  createCard,
  createActionFailure,
  createContinent,
  createGameRulesetDefinition,
  createDomainFailure,
  createGameState,
  createLogEntry,
  createLocalizedError,
  createPlayer,
  createPieceThemeDefinition,
  createResolvedGameConfig,
  createStandardDeck,
  createValidationFailure,
  createTerritory,
  createVictoryRuleDefinition,
  getCardRuleSet,
  standardCardRuleSet,
  standardTradeBonusForIndex,
  validateStandardCardSet
};
